### ISSUE TITLE
Links not working.

### ISSUE THREAD

**Issue by killerclaws12** [Xx-Mohit-xX/Comfi#10]
Hi i tried to look at ur website to join your server but your website is offline if makes sense and your uptime page says the bot is offline. Send me the server invite please.

**Comment by Xx-Mohit-xX** [comment]
> Hi i tried to look at ur website to join your server but your website is offline if makes sense and your uptime page says the bot is offline. Send me the server invite please.

If you would have clicked on server widget on last of the Readme. It would have redirected to my discord but here's the link https://discord.gg/dprDr9hy3X

**Comment by killerclaws12** [comment]
I clicked it and it brought me straight to your website.

**Comment by killerclaws12** [comment]
the widget.
